gcp_profiles:

  - profile_name: stage-europe-west3
    project_id: us-burger-gcp-poc
    zone: europe-west3-b
    bucket: wanna-ml-west3
    service_account: "wanna-ml-testing@us-burger-gcp-poc.iam.gserviceaccount.com"
    labels:
      gcp-profile: stage-europe-west3
