gcp_profiles:

  - profile_name: stage-europe-west3
    project_id: "your-gcp-project-id"
    zone: europe-west3-b
    bucket: "your-staging-bucket-name"
    network: default
    labels:
      gcp-profile: stage-europe-west3
