wanna_project:
  name: wanna-custom-job-sample
  version: 1
  authors: [michal.mrazek@avast.com]

gcp_profiles:
  - profile_name: default
    project_id: cloud-lab-304213
    network: cloud-lab
    zone: europe-west1-b
    bucket: wanna-cloudlab-europe-west1
    service_account: "wanna-dev@cloud-lab-304213.iam.gserviceaccount.com"
    labels:
      some-default: label

tensorboards:
  - name: wanna-sample-dashboard

docker:
  images:
    - build_type: provided_image
      name: tensorflow
      image_url: gcr.io/cloud-aiplatform/training/tf-gpu.2-1:latest
    - build_type: provided_image
      name: debian
      image_url: gcr.io/google-containers/debian-base:1.0.0
  repository: wanna-samples
  cloud_build: true

jobs:
  - name: custom-training-job-with-python-package
    worker:
      python_package:
        docker_image_ref: tensorflow
        package_gcs_uri: "gs://wanna-cloudlab-europe-west1/trainer-0.1.tar"
        module_name: "trainer.task"
      args: ['--epochs=100', '--steps=100', '--distribute=single']
      machine_type: "n1-standard-4"
      gpu:
          accelerator_type: NVIDIA_TESLA_T4
          count: 1
    tensorboard_ref: wanna-sample-dashboard

  - name: custom-training-job-with-containers
    worker:
      container:
        docker_image_ref: debian
        command: ["echo", "'Test'"]

  - name: custom-job-with-containers
    workers:
      - container:
          docker_image_ref: debian
          command: ["echo", "'Test'"]
        machine_type: "n1-standard-4"
        gpu:
          accelerator_type: NVIDIA_TESLA_T4
          count: 1
      - container:
          docker_image_ref: tensorflow
          command: ["echo", "'Test'"]
        machine_type: "n1-standard-4"
        gpu:
          accelerator_type: NVIDIA_TESLA_T4
          count: 1
