wanna_project:
  name: wanna-custom-job-sample
  version: 1
  authors: [michal.mrazek@avast.com]

gcp_settings:
  project_id: us-burger-gcp-poc
  zone: europe-west1-b
  bucket: wanna-ml-west1

tensorboards:
  - name: wanna-sample-dashboard

docker:
  images:
    - build_type: provided_image
      name: tensorflow
      image_url: gcr.io/cloud-aiplatform/training/tf-gpu.2-1:latest
    - build_type: provided_image
      name: debian
      image_url: gcr.io/google-containers/debian-base:1.0.0
  repository: wanna-samples

jobs:
  - name: custom-training-job-with-python-package
    region: europe-west1
    worker:
      python_package:
        docker_image_ref: tensorflow
        package_gcs_uri: "gs://wanna-ml/trainer-0.1.tar.gz"
        module_name: "trainer.task"
      args: ['--epochs=100', '--steps=100', '--distribute=single']
      gpu:
          accelerator_type: NVIDIA_TESLA_V100
          count: 1
    tensorboard_ref: my-nice-tensorboard
    service_account: 966197297054-compute@developer.gserviceaccount.com

  - name: custom-training-job-with-containers
    region: europe-west1
    worker:
      container:
        docker_image_ref: debian
        command: ["echo", "'Test'"]

  - name: custom-job-with-containers
    region: europe-west1
    workers:
      - container:
          docker_image_ref: debian
          command: ["echo", "'Test'"]
#        gpu:
#          accelerator_type: NVIDIA_TESLA_K80
#          count: 1
      - container:
          docker_image_ref: debian
          command: ["echo", "'Test'"]
  #      gpu:
  #        accelerator_type: NVIDIA_TESLA_K80
  #        count: 1
