wanna_project:
  name: notebook-example-1
  version: 1
  authors: [michal.mrazek@avast.com]

gcp_settings:
  project_id: us-burger-gcp-poc
  zone: europe-west4-a
  bucket: wanna-ml

jobs:
  - name: my-simple-job
    region: europe-west1
    worker:
      python_package:
        executor_image_uri: "gcr.io/cloud-aiplatform/training/tf-gpu.2-1:latest"
        package_gcs_uri: "gs://wanna-ml/trainer-0.1.tar.gz"
        module_name: "trainer.task"
      args: ['--epochs=100', '--steps=100', '--distribute=single']
      gpu:
          accelerator_type: NVIDIA_TESLA_V100
          count: 1
  - name: job-with-containers
    region: europe-west1
    worker:
      container:
        image_uri: "gcr.io/google-containers/debian-base:1.0.0"
        command: "echo 'Test'"
      gpu:
        accelerator_type: NVIDIA_TESLA_V100
        count: 1

