wanna_project:
  name: pipeline-pytorch-example-1
  version: 1
  authors: [joao.silva1@avast.com]

gcp_settings:
  project_id: us-burger-gcp-poc
  zone: europe-west4-a
  bucket: joao-gcp-tests
  labels:
  service_account:

docker:
  images:
    - build_type: local_build_image
      name: trainer_image
      context_dir: .
      dockerfile: Dockerfile

    - build_type: local_build_image
      name: predictor_image
      context_dir: predictor
      dockerfile: Dockerfile.serve

pipelines:
  - name: pytorch-text-classification
    pipeline_file: pipelines/pipeline.py
    pipeline_function: pytorch_text_classifier_pipeline
    docker_image_ref: ["trainer_image", "predictor_image"]
    schedule: "0 0 * * *"
